[package]
name = "bytemuck"
description = "A crate for mucking around with piles of bytes."
version = "1.3.0"
authors = ["Lokathor <zefria@gmail.com>"]
repository = "https://github.com/Lokathor/bytemuck"
readme = "README.md"
keywords = ["transmute", "bytes", "casting"]
categories = ["encoding", "no-std"]
edition = "2018"
license = "Zlib OR Apache-2.0 OR MIT"
exclude = ["/scripts/*", "/.travis.yml", "/appveyor.yml", "/bors.toml", "/pedantic.bat"]

[package.metadata.docs.rs]
all-features = true

[features]
# Note: Yeah these names are non-standard, we'll fix it in v2 some day maybe
extern_crate_alloc = []
extern_crate_std = ["extern_crate_alloc"]

[badges]
appveyor = { repository = "Lokathor/bytemuck" }
travis-ci = { repository = "Lokathor/bytemuck" }
