name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test_no_features:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.34.0, stable, beta, nightly]
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test
  build_test_with_features:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.34.0, stable, nightly]
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --all-features
    - name: Test
      run: cargo test --all-features
